data_ingestion:
  datasource:
    type: Oracle
    params:
      user: system
      password: opass1231
      host: localhost
      port: 1521
      service_name: FREEPDB1
      table: fin_ana_data
  vectordb:
    type: ChromaDB
    params:
      persist_directory: ./chromadb
  embedding:
    type: sentence-transformers
    params:
      model: all-MiniLM-L6-v2
      chunk_size: 512
      max_batch_size: 512
llm_inference:
  llm:
    type: OpenAI
    params:
      model: gpt-4o-mini
      max_tokens: 512
      temperature: 0.7
      top_p: 1.0
  prompt_vars: {}
